# Copy this file to /usr/local/etc/uecsgw/config.ini and use it.
# Please change the description to suit your current environment.

[uecs]
Version = 1.00-E10
Room = 1
Region = 1
Order = 1
NodeName = uecsgw01
Port = 16520

[mqtt]
TopicTop = uecs-v1
BrokerHost = mqtt.domain.tld
Port = 1883
User = uecsmqtt
Passwd = password
Id = uecsgw01
